use super::consts::NAMED_ENCODERS;
use crate::options::EncodeOptions;
use crate::options::CompressionLevel;

use clap::ValueEnum;

#[test]
fn test_blob() {
  let payload = "ZTQ2YTYyMTBmMTQxYTI1Nzk4NWNkYzFiMmQzMmVjODFlOWIzZTRjNTU0Zjc0NjM4Y2IyNWU1NTQ4ODdlZjI5NmNhMGI2NjQ0NDY0
YTAzYmFkODg2YTkzOWJhOTIxZjBhYjRlMTgwMmZhZDc2ODliNzkzN2RlYmUxYjJjZWEzZjdkZTMyZDM4ZWNmMWFjMjcyOTE1ZmZj
ODdiODQ0MTM1YTI4MWVkNmEyYzAwYTFjMDMzZDhhYmEyM2MwYzE5MjE1ODE1MTg5MzUzZWFjMzBmOTkxYWQ0ODIxNjNiMmU0Nzc5
MjBlNTM5ZWI5NmMwMWNkMzNlZDkxYmRjNGJlYWJlMjg0ZGQ5NjgxN2I3NTVkM2Q1Mjc2Yjk2NDhhZDY2YzQ3NTU3ZGZjZDYyMDAy
NjE3NzVmZjQ1ZjA5NzViMGFjMmQwMjY1Y2I2YWEzNDQyMGU0MjZjMmVjMmJjOWEwNmVjMWY2NTAzOGQ2Y2ZiZWJkZDg1OTc0NDJl
OGRlZjdlYzVhZTNkMjgwMWU4YzE3OTk0MGZiYmUzOWJhYjU3ZGMwMDBlY2RiZGM2OGEzMjU2MzE3MDQ0ZWMzNDFlN2UyZjc1MTE4
NmNlZDMyYzc5YzZhM2FhZGM2MjUyMzYxYWJhOTQ4NjFjNWViZmQzYWFiMTI2M2YyOGFkY2UyMTdiZmI3ZjE4ZjQ4ZGM1NmE0MTAy
OTk0Mjc1NzJiZmI1YjBjYzlmYjc2YWI5NjIyOTM5MWRjZjlmOWE3NTI2YzQzYWZjMjlmMTBlZTYxMTQ4ZTM5MTg4ZmRjZGVjZDY4
YTM4ZGRlYjgzZGEwNWZmMGMwZjM2MmRkMjM3YThiMWMxNjdhZDMzY2I2ZmFmYmU0ODhhYWNjMjA0YmU3ODc1ZTE4NDg5NjM5ZjA3
ZDlmMDkyZDY0MzA5NDQ5MDI1NDkwZTcxM2NhNTJhNTIwNDVmNDVlMDRhNzdlZjI0YjRkYWM3ZTY4NDVjOGUxYTIzOWMwZDE1ODg3
ZjA0MGI2MGQ0ZGEzMGY4MTE5ZGQyMDRiYmI1YWZmZWUyMGZkNDZiYWYzMWI2NDU1ZDZiM2ZmZmIyZDVkNzRkNzYxODg3N2M4OGU4
NzQ4NWI5ODRiNThlYzRiN2E5ZDUzZGQ3Mjk4YjlmNTBjYWRmMzdlZDczYzJjZDMwMjRjNjY5OWQ0NjEwYjI1ZjUzMGYyYmM4Y2M0
MTAxNTgwNGZhNTE3NzJkMzIwZDJmNjlmZjA3YzIxNjk5M2MxMmRkMWViZTM2ZmFiYTQ0Y2UxODhhYjdiNWU5ZGU0NGJjYzAyMjk1
OTMzNGVlMGE1MjUwMzg5NDJkNzE1MzQxY2ZiMTZjYTgwYmQyMzdjZjFlODdhNzZjOGE4ZmZlNjc5OWZiMGNmNzljYmRmODk4ZDJl
ZTFmMWMzMjBlYTFiM2VkZTIyYjBjNjFlOTM0NmYyZGMwNDc4ZjNkZTI5OTY3MDhkOGVhYzVjODVjYzRlNDQ5MTg4NDVjZDU3NDlm
YjEyZmYzMmFkOWJkNjUzMzE1OTIzNjE4MmJlNmUxYmFmNmI2MWNlYzg0NWFhNGYwZmZiY2VjOTAyNzM4M2VhMmVjOGUxMzM4OGJj
MWNkN2JhYjE1MGRkYTRmZGU5OGFmYjI1MmZjOGIzZjBlYjdlMzY3YjljODJiMzMyOGUzYmIyN2YyMjlmNGRjNDI0OTNkZDAwYjcw
NzgzZmNkZTMwYWE3MzYxZjI5NDllNWYwY2NhMjg4OTZmOTEzYTkxN2EwNDk4YTk0NjI5OTFlYjM5ODg3ZjQ0NDM5MDM5MzJkZmM5
OTFhYmRlODQzZmFkYmY0YTAyMmUzMWVkOTI0OTg3Y2JhZGVjYmI5ODAxNDdlYmU3NGI4ZTg5NWRmNWIwZTMxZDJiNDcwNWZiMjUy
NzQyZmY5NGIwYWZkMjAzMTcwY2IwNzVlNjQ0YWJlNDkzMGFiOTc4MDgyNTU2ZjgyYzI2NTUwMWZkMWNmZTY3OTc5NmJkY2U2MDFl
MzZjOTY4Y2UxOWIyZGJiYjBkZWUwZjI4YzNiZTRhZTJhYzU3YTY3ODQ3ZGUzYTIxOGMxMmEzYWM3MGUxMGQ3MTQxZTZlYmNmYjQ5
YWRlOWNmMDdhM2Y4MmZmM2JiMGU3YzI1OGM2MDQzYzAwZDVmZDU0YTgwMzI5NGU2YjU4MjBhM2UyOTMxMWQ5MzgwZGZmNTRlMWM2
MmNmN2ZmNjI3ODY1ZTdkOWY0NDRiMGZlZGQ5YTM0NGFmODIwM2U0ZTMyOGViMWRjOGUzZTg2ODI3MjgwYzlmMjU3OWNiYTE4MDFj
MGFmYmI4NGM0NTRhNDI4NDZhYTg2NDg2NGM4YzE3ZDczZjgxZDUyMzM2MTU3ZmEyMGFmMDk5ZDgzNjRlYzFhOGIxZjYyNTE0ODQ4
NWEyY2VmNDNhMWM0YzZiZWI2NjkxMjJiMmY2Nzk1NmFhODA1MmZkYzI2YmRlZWI4NTRlODlmYWI3YjUyZTRkNmQwODY1YWUxZWFi
YTcxNWM3YWZhMTVkYjAwNTNiZDZmOWQ3MGRlNTJjMmY5MDAyZjU0M2VmNzc5YzdhNTY1OWE0NTlmNTA3ZTI5YWFjMTQ5MDU0NDM5";

  for (name, encoder) in NAMED_ENCODERS {
    for level in CompressionLevel::value_variants() {
        if *name == "bpe_dummy" {
            continue;
        }
        let encoded = match encoder.encode(&payload, &EncodeOptions { level: level.clone() }) {
            Ok(encoded) => encoded,
            Err(e) => {
                panic!("Encoding failed: {}: {} -> {}", name, payload, e);
            }
        };
        let decoded = match encoder.decode(&encoded) {
            Ok(decoded) => decoded,
            Err(e) => {
                panic!("Decoding failed: {}: {} -> {}", name, encoded, e);
            }
        };
        assert_eq!(decoded, payload);
        println!("{}: {:?} -> OK", name, level);
    }
  }
}
