#!/usr/bin/env python3
"""
Generate hardcoded encoder-alphabet roundtrip fixtures for Rust tests.

For each non-adaptive encoder: fetch its alphabet and emit Rust slices of
(encoder_name, alphabet, encoded) tuples for:
  - same encoder (generated_alphabet_roundtrips.rs)
  - adaptive encoder (generated_adaptive_alphabet_roundtrips.rs)

usage (from repo root):
  python3 scripts/generate_static_tests.py
  python3 scripts/generate_static_tests.py --binary ./rust/target/release/unipress
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).parent.parent
_DEFAULT_BINARY = _REPO_ROOT / "rust" / "target" / "release" / "unipress"
_TEST_DIR = _REPO_ROOT / "rust" / "src" / "encoders" / "test"
_DEFAULT_OUTPUT = _TEST_DIR / "generated_alphabet_roundtrips.rs"
_DEFAULT_OUTPUT_ADAPTIVE = _TEST_DIR / "generated_adaptive_alphabet_roundtrips.rs"


def rust_string_literal(s: str) -> str:
  """Escape s for a Rust double-quoted string literal."""
  parts: list[str] = ['"']
  for ch in s:
    o = ord(ch)
    if ch == "\\":
      parts.append("\\\\")
    elif ch == '"':
      parts.append('\\"')
    elif ch == "\n":
      parts.append("\\n")
    elif ch == "\r":
      parts.append("\\r")
    elif ch == "\t":
      parts.append("\\t")
    elif ch == "\0":
      parts.append("\\0")
    elif o < 0x20 or o == 0x7F:
      parts.append(f"\\u{{{o:04X}}}")
    else:
      parts.append(ch)
  parts.append('"')
  return "".join(parts)


def run_unipress(
  binary: Path,
  args: list[str],
  *,
  input_text: str | None = None,
) -> str:
  result = subprocess.run(
    [str(binary), *args],
    input=input_text,
    capture_output=True,
    text=True,
    cwd=_REPO_ROOT,
  )
  if result.returncode != 0:
    raise RuntimeError(
      f"unipress {' '.join(args)} failed ({result.returncode}): {result.stderr.strip()}"
    )
  # CLI uses println for --alphabet; do not treat that trailing newline as payload.
  out = result.stdout
  if "--alphabet" in args and out.endswith("\n"):
    out = out[:-1]
  return out


def list_encoders(binary: Path) -> list[str]:
  out = run_unipress(binary, ["--list-encoders"])
  return [line.strip() for line in out.splitlines() if line.strip() != "adaptive"]


def encoder_alphabet(binary: Path, name: str) -> str:
  return run_unipress(binary, ["--encoder", name, "--alphabet"])


def encode_payload(binary: Path, name: str, payload: str) -> str:
  return run_unipress(binary, ["--encoder", name], input_text=payload)


def generate_roundtrips(
  binary: Path,
  *,
  encode_as: str | None = None,
) -> list[tuple[str, str, str]]:
  """encode_as=None: encode each alphabet with its own encoder; else use encode_as."""
  pairs: list[tuple[str, str, str]] = []
  for name in list_encoders(binary):
    encoder = encode_as if encode_as is not None else name
    print(f"encoding alphabet via {encoder}: {name}", file=sys.stderr)
    alphabet = encoder_alphabet(binary, name)
    encoded = encode_payload(binary, encoder, alphabet)
    pairs.append((name, alphabet, encoded))
  return pairs


def render_rust(
  pairs: list[tuple[str, str, str]],
  *,
  const_name: str,
  doc: str,
) -> str:
  lines = [
    "// Generated by scripts/generate_static_tests.py. Do not edit by hand.",
    "",
    f"/// {doc}",
    f"pub const {const_name}: &[(&str, &str, &str)] = &[",
  ]
  for name, alphabet, encoded in pairs:
    lines.append(
      f"    ({rust_string_literal(name)}, {rust_string_literal(alphabet)}, "
      f"{rust_string_literal(encoded)}),"
    )
  lines.append("];")
  lines.append("")
  return "\n".join(lines)


def parse_args() -> argparse.Namespace:
  parser = argparse.ArgumentParser(
    description="Generate Rust alphabet roundtrip test fixtures.",
  )
  parser.add_argument(
    "--binary",
    type=Path,
    default=_DEFAULT_BINARY,
    help=f"Path to unipress binary (default: {_DEFAULT_BINARY}).",
  )
  return parser.parse_args()


def write_fixtures(
  binary: Path,
  *,
  encode_as: str | None,
  output: Path,
  const_name: str,
  doc: str,
) -> int:
  pairs = generate_roundtrips(binary, encode_as=encode_as)
  output.write_text(
    render_rust(pairs, const_name=const_name, doc=doc),
    encoding="utf-8",
  )
  print(f"wrote {len(pairs)} roundtrips to {output}", file=sys.stderr)
  return len(pairs)


def main() -> None:
  args = parse_args()
  if not args.binary.is_file():
    print(f"error: binary not found: {args.binary}", file=sys.stderr)
    print("build with: cd rust && cargo build --release", file=sys.stderr)
    sys.exit(1)

  write_fixtures(
    args.binary,
    encode_as=None,
    output=_DEFAULT_OUTPUT,
    const_name="ENCODER_ALPHABET_ROUNDTRIPS",
    doc="(encoder_name, alphabet, encoded_alphabet) for each static encoder.",
  )
  write_fixtures(
    args.binary,
    encode_as="adaptive",
    output=_DEFAULT_OUTPUT_ADAPTIVE,
    const_name="ADAPTIVE_ALPHABET_ROUNDTRIPS",
    doc="(source encoder name, alphabet, alphabet encoded via adaptive) for each static encoder.",
  )


if __name__ == "__main__":
  main()
